### ISSUE TITLE
LEGUP does not work unless run as Admin via PowerShell

### ISSUE THREAD

**Issue by kd2eom** [Bram-Hub/Legup#14]
On some Windows PCs, when you try to open LEGUP, you receive the following error: 
![image](https://user-images.githubusercontent.com/29665790/66360859-8e8d7e00-e94a-11e9-8e3e-13a85e183d26.png)

When you attempt to run the program via the command line, you receive this error:
![image (1)](https://user-images.githubusercontent.com/29665790/66397021-f96da200-e9a8-11e9-943b-d2829cef70cf.png)

The program only launches if you open a command prompt/powershell window **as administrator** and then attempt to launch the program from the command line.

**Comment by Alapocas** [comment]
One of the reason is your username. I see that you directory was 13 char long in the error message and it was 11 char long in you cmd. That might be why the java program is not able to create the log file. I am guessing you have a space in your username.  So the code will translate the space to "%20", which would cause some problems. When you execute in administrator mode, you would observer the new directory will be created with the log file inside.
If fixing the username issue does not solve the problem, then it must be that you did not grant enough permission to your folder that it is not allowed to create new file in it. Therefore, you need to go to properties of the folder and grant full control to user. Then you would be able to run the jar file.

**Comment by kd2eom** [comment]
Thanks, I do have a space in my username, but I feel that that's a very common use case that the program should be able to handle (I think Windows does that itself when you create a user with your Microsoft account, which is the default option in Windows 10 - your username is your first name <space> last name); additionally, I don't think Windows will let me change the username without creating an entirely new account, which is not feasible. I could just run it as admin all the time but I feel that I shouldn't need to do that (and the average user probably wouldn't know to try that).

**Comment by Alapocas** [comment]
As I looked into the code that generated the logfile, it seems the path was obtained by getting the URL of the resource and then convert that to file. However, URL encoding will make space into "%20". So I made a fix to that code to further convert URL to URI and then to File so that the path returned will handle the space correctly.

**Comment by YoshikoJanai** [comment]
Fix has been merged into master https://github.com/Bram-Hub/Legup/pull/27
