### ISSUE TITLE
[BUG] Short Truth-Table v Elimination rules checks out when it should not

### ISSUE THREAD

**Issue by Bram28** [Bram-Hub/Legup#351]
### Description

Short Truth-Table v Elimination rules checks out when it should not

### Steps to Reproduce

Open a puzzle with a green (true) v .  Make left or right (or both) side green and justify with v Elimination. That checks out ... but it should not. 

### Expected Behavior

What should happen is that you get a red transition: not a good inference!

### Screenshots

Start:

![image](https://user-images.githubusercontent.com/2414519/198093503-0e3fbabd-31a1-4ca6-a564-fbf4b4d97acf.png)

Make left side green:

![image](https://user-images.githubusercontent.com/2414519/198094231-43bffcef-8bca-422d-bea3-5a74580773d4.png)

Justify with v elim

![image](https://user-images.githubusercontent.com/2414519/198094334-1aef2a04-8126-4dd0-a6a4-3cd0c1d3d7f5.png)

Oops!  Transition is green. Nope, this is not right!

### Puzzle Files

[STT19OrEliminationBug.zip](https://github.com/Bram-Hub/Legup/files/9872246/STT19OrEliminationBug.zip)

### Additional Context

Chase says that the v Elim rule at some point calls the v Intro rule!

**Comment by N-Desmarais** [comment]
### Bug Description

When proving an elimination rule the software currently disproves if and only if a contradiction can be found using the corresponding contradiction rule. In this example the corresponding contradiction to Or-Elimination is Or-Contradiction.
 
 This means the transition will only be invalid if the affected cells follow one of these 3 patterns:
 
![image](https://user-images.githubusercontent.com/55117352/198160979-bb94ca1a-0f1f-4dde-978f-80ec2cdd268e.png)

In our example the affected cells do not follow any of the above patterns:

![image](https://user-images.githubusercontent.com/55117352/198161143-950330f1-e103-4bc2-a4f3-2d3813c7177d.png)

This means no Or-Contradiction is found and therefore the software incorrectly accepts the justification for the transition.

### How To Correct

This bug is not specific to Or-Elimination it applies to all elimination rules. The issue lies in the fact that not having a corresponding contradiction doesn't imply the justification for the given transition is correct. Another example:

reproduced with bi conditional elim:
![image](https://user-images.githubusercontent.com/55117352/198164494-21c500d7-d81e-4020-bc0b-597b81c86b17.png)

In order to resolve this, the process for justifying an elimination rule needs to be completely refactored to follow a logically valid set of steps. This likely means enumerating the patterns that are logically justified and checking against those instead of the corresponding contradiction. Will discuss more with chase about implementation details

**Comment by Bram28** [comment]
Thanks for looking into this so quickly! If the rule is implemented as you describe, then your analysis is exactly correct: A claim is not forced to have a certain truth-value just because no contradiction is found when it has that truth-value. The latter only means that the claim can *possibly* have that truth-value ('possible' defined relative to the local context of the applied rule), but that does not make it *necessary*. 

What the implementation should do instead is to check that if we give the claim its *opposite* truth-value, then we *do* get a contradiction. So, for example, say you have a false disjunction, and you indicate that this means that the left side is also false. The rule should now consider what happens if that left side is true. And, when it does, it finds a v-Contradiction. So: the claim cannot be true, and is therefore indeed forced to be false. So, we can have these basic rules rely on contradiction rules ... just not how it is currently done!

**Comment by N-Desmarais** [comment]
Submitted a fix that applies the proper negation before checking for contradiction, program shows expected behavior:

Invalid applications of rules no longer creating valid board states:

![Screenshot_2](https://user-images.githubusercontent.com/55117352/200178478-36a512ae-4740-4735-baa6-caaf4da6a63f.png)

Getting the correct error message for misuse of a rule

![Screenshot_1](https://user-images.githubusercontent.com/55117352/200178490-bf5a9643-deaf-496c-8381-42ded11fc5a4.png)

Valid applications of rules working properly:

![Screenshot_11](https://user-images.githubusercontent.com/55117352/200178501-39b57c00-5475-41e4-9d6a-d4be0743056d.png)

Not sure I've seen enough to weigh in on whether or not the case/contradiction rules can be implemented universally. That being said if it was possible this technique would work universally, and any puzzle specific implementations could be trimmed out.
