### ISSUE TITLE
Unreachable White Region Bug

### ISSUE THREAD

**Issue by charlestian23** [Bram-Hub/Legup#46]
![image](https://user-images.githubusercontent.com/46334090/136407599-846c211b-5641-4dc1-b716-b9e1ef1e0d92.png)

In the second step, use of the Unreachable White Region justification is incorrectly marked as valid. It seems to be that the unreachable square rule is sensitive to existing whites in a bad way, as the second step shows that changing any square to black will still make the rule say everything is valid.

[nurikabe2 - Unreachable (checks out when it should not).zip](https://github.com/Bram-Hub/Legup/files/7304744/nurikabe2.-.Unreachable.checks.out.when.it.should.not.zip)

**Comment by Bram28** [comment]
I think the bug is this:  The Unreachable White Region rule is a basic rule and is probably implemented on the basis of the Can't Reach White Cell contradiction rule (wow! That is already confusing ... maybe we should call the basic rule: Unreachables Are Black). Specifically, the Unreachable White Region rule is probably coded to work as follows: assume that all the squares that the user just made black are white instead, and see if there is now a Unreachable White Region contradiction. And in this case: yes, there is!  Because that existing white square that was placed in the top left in the first step is indeed Unreachable. And so therefore the Unreachable White Region basic rule checks out.      .... OK, so that should be changed to: see if any of the squares that the user just made black would be unreachable if we assume they are white (i.e. it should not see if any existing white squares are unreachable).    

Now, this does mean that the implementation of the basic rule no longer can use a *simple* reference to the indicated contradiction rule ... so that's a real bummer as far as coding basic rules in LEGUP in terms of contradiction rules so. But maybe we could do the following: the Can't Reach White Cell contradiction rule gets a parameter that is the square under consideration: it sees whether *that* specific cell is indeed unreachable, rather than *any* cell being unreachable. And, compatible with that, maybe we could even force the user to indicate which specific cell they think is unreachable (which might be a good thing: with a user not having to specify where on the board there is some contradiction going on, there is a danger a user could just open the contradiction rule panel, and simply click on any of the contradiction rules in order and see if any checks out!)
