### ISSUE TITLE
Nurikabe White Bottle Neck Rule Bug

### ISSUE THREAD

**Issue by charlestian23** [Bram-Hub/LEGUP#95]
## Current Behavior
When multiple consecutive cells are selected for White Bottle Neck rule, Legup does not mark all the cells as valid, even when they are. Attached is an image of an example:
![image](https://user-images.githubusercontent.com/46334090/157699317-6fc266f8-6eae-4020-94a3-d8c444a95565.png)

Note: I am not sure if this bug is also present for Black Bottle Neck rule, but since the logic of those two cells are quite similar, it could be possible.

## Expected Behavior
All cells should be marked valid if they pass the White Bottle Neck rule.

## Steps to Reproduce
Mark all cells that should be white due to bottlenecking as valid. 

Note the the attached file only works on the pre-UID version of Legup.
[nurikabe_white_escape_bug.zip](https://github.com/Bram-Hub/Legup/files/8224919/nurikabe_white_escape_bug.zip)

**Comment by walkingjason** [comment]
This issue happens because when multiple grids are changed simultaneously, these grids are checked against the selected rule independently. This is not a problem with other rules.  However, White Bottle Neck Rule and Black Bottle Neck Rule need to check the grids in a certain order. For example, for the board in the initial comment to pass, it is required that the rule first check the green grid (0, 11), update a temporary board, and check the red grid (0, 10). We currently don't have mechanisms to do this.

What is the expected behavior? Should we forbid selecting multiple grids for the White/Black Bottle Neck Rule?
@charlestian23 @Bram28

**Comment by Bram28** [comment]
Yes, in this case it would make sense to first check the green square, and then the red square, but that is *not* how I want this rule to be implemented.  If the user makes multiple changes to the board, then *each* change should be verified independently of the other changes. That is how every Legup rule should be implemented. So yes, it is ok for the user to make multiple changes, but each change should be checked out independently. And in this case, the red square *should* check out by itself, because if you make it black, then that those two white cells in the top right can never become a room with a number. The fact that the square on (0,11) is unknown does not change that fact, and the implementation of the rule should indeed be able to take into account such unknowns.  And so no, the user should not be required to first fill out (0,11) and then (0,1))... if the use would leave (0,11) alone and make (0,11) white the rule should still check out. And in this case making both (0,11) and (0,10) white should check out because in each case it is true that if you would make it black you get a contradiction.  In fact, we should have a ready-made contradiction rule that checks for such isolated whites .... it should be the 'No Number' Contradiction rule. So as long as 'No number' is implemented correctly, you simply use that routine to check that if the square was black, you'd get that 'No Numbner' contradiciton.  .... OK, and I just checked and the 'No Number' contradiction rule is *not* taking into account the unknown squares .. so that's the real problem here: the 'No Number' contradiction rule should be changed so it can take into account any unknown squares!
